on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build
        run: |
          scripts/buildprod.sh

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build on Cloud
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --project=pacific-engine-460523-r9
