on:
  push:
    branches:
      - main

env:
  VERSION: v0.1.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Build
        run: |
          scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build on Cloud
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_VERSION=$VERSION

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image=australia-southeast1-docker.pkg.dev/pacific-engine-460523-r9/notely-ar-repo/notely:$VERSION \
            --region=australia-southeast1 \
            --allow-unauthenticated \
            --project=pacific-engine-460523-r9 \
            --max-instances=4 \
            --platform=managed \
            --quiet
