on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build
        run: |
          scripts/buildprod.sh

      - name: Build on Cloud
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml
